FROM node:18

WORKDIR /app

COPY ./packages/seeder/package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

COPY ./packages/seeder .
COPY ./packages/prisma/schema.prisma .

RUN npx prisma generate
RUN npm run build

CMD ["sh", "-c", "node --experimental-specifier-resolution=node /app/dist/index.js"]